// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: calc.proto

package calculator

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_NotSpecified Operation = 0
	Operation_Plus         Operation = 1
	Operation_Substraction Operation = 2
	Operation_Multiply     Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "NotSpecified",
		1: "Plus",
		2: "Substraction",
		3: "Multiply",
	}
	Operation_value = map[string]int32{
		"NotSpecified": 0,
		"Plus":         1,
		"Substraction": 2,
		"Multiply":     3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_calc_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_calc_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_calc_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_Calc  Type = 0
	Type_Print Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Calc",
		1: "Print",
	}
	Type_value = map[string]int32{
		"Calc":  0,
		"Print": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_calc_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_calc_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_calc_proto_rawDescGZIP(), []int{1}
}

type CalcRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Instruction   []*CalcRequest_Instruction `protobuf:"bytes,1,rep,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalcRequest) GetInstruction() []*CalcRequest_Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

type CalcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*CalcResponse_Item   `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse) Reset() {
	*x = CalcResponse{}
	mi := &file_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse) ProtoMessage() {}

func (x *CalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse.ProtoReflect.Descriptor instead.
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return file_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalcResponse) GetItem() []*CalcResponse_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CalcResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CalcRequest_Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=calculator.Type" json:"type,omitempty"`
	Var   string                 `protobuf:"bytes,2,opt,name=var,proto3" json:"var,omitempty"`
	Op    *Operation             `protobuf:"varint,3,opt,name=op,proto3,enum=calculator.Operation,oneof" json:"op,omitempty"` // "+","-","*"
	// Types that are valid to be assigned to Left:
	//
	//	*CalcRequest_Instruction_LeftLiteral
	//	*CalcRequest_Instruction_LeftVar
	Left isCalcRequest_Instruction_Left `protobuf_oneof:"left"`
	// Types that are valid to be assigned to Right:
	//
	//	*CalcRequest_Instruction_RightLiteral
	//	*CalcRequest_Instruction_RightVar
	Right         isCalcRequest_Instruction_Right `protobuf_oneof:"right"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest_Instruction) Reset() {
	*x = CalcRequest_Instruction{}
	mi := &file_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest_Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest_Instruction) ProtoMessage() {}

func (x *CalcRequest_Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest_Instruction.ProtoReflect.Descriptor instead.
func (*CalcRequest_Instruction) Descriptor() ([]byte, []int) {
	return file_calc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CalcRequest_Instruction) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Calc
}

func (x *CalcRequest_Instruction) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *CalcRequest_Instruction) GetOp() Operation {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return Operation_NotSpecified
}

func (x *CalcRequest_Instruction) GetLeft() isCalcRequest_Instruction_Left {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *CalcRequest_Instruction) GetLeftLiteral() int64 {
	if x != nil {
		if x, ok := x.Left.(*CalcRequest_Instruction_LeftLiteral); ok {
			return x.LeftLiteral
		}
	}
	return 0
}

func (x *CalcRequest_Instruction) GetLeftVar() string {
	if x != nil {
		if x, ok := x.Left.(*CalcRequest_Instruction_LeftVar); ok {
			return x.LeftVar
		}
	}
	return ""
}

func (x *CalcRequest_Instruction) GetRight() isCalcRequest_Instruction_Right {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *CalcRequest_Instruction) GetRightLiteral() int64 {
	if x != nil {
		if x, ok := x.Right.(*CalcRequest_Instruction_RightLiteral); ok {
			return x.RightLiteral
		}
	}
	return 0
}

func (x *CalcRequest_Instruction) GetRightVar() string {
	if x != nil {
		if x, ok := x.Right.(*CalcRequest_Instruction_RightVar); ok {
			return x.RightVar
		}
	}
	return ""
}

type isCalcRequest_Instruction_Left interface {
	isCalcRequest_Instruction_Left()
}

type CalcRequest_Instruction_LeftLiteral struct {
	LeftLiteral int64 `protobuf:"varint,4,opt,name=left_literal,json=leftLiteral,proto3,oneof"`
}

type CalcRequest_Instruction_LeftVar struct {
	LeftVar string `protobuf:"bytes,5,opt,name=left_var,json=leftVar,proto3,oneof"`
}

func (*CalcRequest_Instruction_LeftLiteral) isCalcRequest_Instruction_Left() {}

func (*CalcRequest_Instruction_LeftVar) isCalcRequest_Instruction_Left() {}

type isCalcRequest_Instruction_Right interface {
	isCalcRequest_Instruction_Right()
}

type CalcRequest_Instruction_RightLiteral struct {
	RightLiteral int64 `protobuf:"varint,6,opt,name=right_literal,json=rightLiteral,proto3,oneof"`
}

type CalcRequest_Instruction_RightVar struct {
	RightVar string `protobuf:"bytes,7,opt,name=right_var,json=rightVar,proto3,oneof"`
}

func (*CalcRequest_Instruction_RightLiteral) isCalcRequest_Instruction_Right() {}

func (*CalcRequest_Instruction_RightVar) isCalcRequest_Instruction_Right() {}

type CalcResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Var           string                 `protobuf:"bytes,1,opt,name=var,proto3" json:"var,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse_Item) Reset() {
	*x = CalcResponse_Item{}
	mi := &file_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse_Item) ProtoMessage() {}

func (x *CalcResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse_Item.ProtoReflect.Descriptor instead.
func (*CalcResponse_Item) Descriptor() ([]byte, []int) {
	return file_calc_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CalcResponse_Item) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *CalcResponse_Item) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_calc_proto protoreflect.FileDescriptor

const file_calc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"calc.proto\x12\n" +
	"calculator\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe8\x02\n" +
	"\vCalcRequest\x12E\n" +
	"\vinstruction\x18\x01 \x03(\v2#.calculator.CalcRequest.InstructionR\vinstruction\x1a\x91\x02\n" +
	"\vInstruction\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.calculator.TypeR\x04type\x12\x10\n" +
	"\x03var\x18\x02 \x01(\tR\x03var\x12*\n" +
	"\x02op\x18\x03 \x01(\x0e2\x15.calculator.OperationH\x02R\x02op\x88\x01\x01\x12#\n" +
	"\fleft_literal\x18\x04 \x01(\x03H\x00R\vleftLiteral\x12\x1b\n" +
	"\bleft_var\x18\x05 \x01(\tH\x00R\aleftVar\x12%\n" +
	"\rright_literal\x18\x06 \x01(\x03H\x01R\frightLiteral\x12\x1d\n" +
	"\tright_var\x18\a \x01(\tH\x01R\brightVarB\x06\n" +
	"\x04leftB\a\n" +
	"\x05rightB\x05\n" +
	"\x03_op\"\x8d\x01\n" +
	"\fCalcResponse\x121\n" +
	"\x04item\x18\x01 \x03(\v2\x1d.calculator.CalcResponse.ItemR\x04item\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x1a.\n" +
	"\x04Item\x12\x10\n" +
	"\x03var\x18\x01 \x01(\tR\x03var\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value*G\n" +
	"\tOperation\x12\x10\n" +
	"\fNotSpecified\x10\x00\x12\b\n" +
	"\x04Plus\x10\x01\x12\x10\n" +
	"\fSubstraction\x10\x02\x12\f\n" +
	"\bMultiply\x10\x03*\x1b\n" +
	"\x04Type\x12\b\n" +
	"\x04Calc\x10\x00\x12\t\n" +
	"\x05Print\x10\x012]\n" +
	"\n" +
	"Calculator\x12O\n" +
	"\x04Calc\x12\x17.calculator.CalcRequest\x1a\x18.calculator.CalcResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/calcB\xa4\x01\x92A\x8f\x01\x12z\n" +
	"\x16Калькулятор\x12YgRPC / http приложение для подсчета и вывода значений2\x051.0.0\x1a\x0elocalhost:8080*\x01\x01Z\x0f/pkg/calculatorb\x06proto3"

var (
	file_calc_proto_rawDescOnce sync.Once
	file_calc_proto_rawDescData []byte
)

func file_calc_proto_rawDescGZIP() []byte {
	file_calc_proto_rawDescOnce.Do(func() {
		file_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calc_proto_rawDesc), len(file_calc_proto_rawDesc)))
	})
	return file_calc_proto_rawDescData
}

var file_calc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calc_proto_goTypes = []any{
	(Operation)(0),                  // 0: calculator.Operation
	(Type)(0),                       // 1: calculator.Type
	(*CalcRequest)(nil),             // 2: calculator.CalcRequest
	(*CalcResponse)(nil),            // 3: calculator.CalcResponse
	(*CalcRequest_Instruction)(nil), // 4: calculator.CalcRequest.Instruction
	(*CalcResponse_Item)(nil),       // 5: calculator.CalcResponse.Item
}
var file_calc_proto_depIdxs = []int32{
	4, // 0: calculator.CalcRequest.instruction:type_name -> calculator.CalcRequest.Instruction
	5, // 1: calculator.CalcResponse.item:type_name -> calculator.CalcResponse.Item
	1, // 2: calculator.CalcRequest.Instruction.type:type_name -> calculator.Type
	0, // 3: calculator.CalcRequest.Instruction.op:type_name -> calculator.Operation
	2, // 4: calculator.Calculator.Calc:input_type -> calculator.CalcRequest
	3, // 5: calculator.Calculator.Calc:output_type -> calculator.CalcResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_calc_proto_init() }
func file_calc_proto_init() {
	if File_calc_proto != nil {
		return
	}
	file_calc_proto_msgTypes[2].OneofWrappers = []any{
		(*CalcRequest_Instruction_LeftLiteral)(nil),
		(*CalcRequest_Instruction_LeftVar)(nil),
		(*CalcRequest_Instruction_RightLiteral)(nil),
		(*CalcRequest_Instruction_RightVar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calc_proto_rawDesc), len(file_calc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calc_proto_goTypes,
		DependencyIndexes: file_calc_proto_depIdxs,
		EnumInfos:         file_calc_proto_enumTypes,
		MessageInfos:      file_calc_proto_msgTypes,
	}.Build()
	File_calc_proto = out.File
	file_calc_proto_goTypes = nil
	file_calc_proto_depIdxs = nil
}
