syntax = "proto3";

package calculator;

option go_package = "/pkg/calculator";

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Калькулятор"
    version: "1.0.0"
    description: "gRPC / http приложение для подсчета и вывода значений"
  }
  host: "localhost:8080"
  schemes: HTTP
};

service Calculator {
  rpc Calc(CalcRequest) returns (CalcResponse) {
    option(google.api.http) = {
      post:"/api/calc"
      body: "*"
    };
  }
}

message CalcRequest {
  repeated Instruction instruction = 1;

  message Instruction{
    Type type = 1;
    string var = 2;
    optional Operation op = 3; // "+","-","*"

    oneof left {
      int64 left_literal = 4;
      string left_var = 5;
    }
    oneof right {
      int64 right_literal = 6;
      string right_var = 7;
    }
  }
}

message CalcResponse{
  repeated Item item = 1;

  message Item {
    string var = 1;
    int32 value = 2;
  }

  int32 duration = 3;
}

enum Operation {
  NotSpecified = 0;
  Plus = 1;
  Substraction = 2;
  Multiply = 3;
}

enum Type {
  Calc = 0;
  Print = 1;
}
